import { Colors } from '@/constants/colors';
import { Spacing } from '@/constants/spacing';
import { FontFamily, FontSize } from '@/constants/typography';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
    backgroundColor: Colors.white,
  },
  backButton: {
    padding: Spacing.sm,
  },
  headerTitle: {
    fontSize: FontSize.lg,
    fontWeight: '600',
    color: Colors.textPrimary,
    fontFamily: FontFamily.montserratSemiBold,
  },
  saveButton: {
    padding: Spacing.sm,
  },
  saveText: {
    fontSize: FontSize.sm,
    color: Colors.primary,
    fontWeight: '600',
    fontFamily: FontFamily.poppinsSemiBold,
  },
  tabsScroll: {
    paddingHorizontal: 0,
    margin: 0,
  },
  tabsContent: {
    flexDirection: 'row',
    paddingHorizontal: Spacing.lg,
    gap: 0,
  },
  tabItem: {
    paddingTop: Spacing.sm,
    paddingBottom: 4,
    paddingHorizontal: Spacing.md,
    position: 'relative',
    height: 32,
  },
  tabText: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.montserratMedium,
    color: Colors.textSecondary,
    textAlignVertical: 'center',
    lineHeight: 14,
    includeFontPadding: false,
  },
  tabTextActive: {
    color: Colors.textPrimary,
    fontFamily: FontFamily.montserratSemiBold,
  },
  tabIndicator: {
    position: 'absolute',
    bottom: -1,
    left: Spacing.md,
    right: Spacing.md,
    height: 2,
    backgroundColor: Colors.primary,
    borderRadius: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    paddingTop: 0,
    marginTop: 0,
  },
  descBlock: {
    paddingVertical: 0,
    marginTop: 0,
    marginBottom: 0,
  },
  artRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.sm,
    marginTop: 6,
    marginBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.slate200,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Spacing.md,
  },
  avatarInitials: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.poppinsSemiBold,
    color: Colors.slate600,
  },
  nameContainer: {
    flex: 1,
  },
  name: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    marginBottom: 2,
  },
  subtext: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.montserratRegular,
    color: Colors.textSecondary,
  },
  amountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 80,
  },
  dollarPrefix: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    marginRight: 2,
  },
  amountInput: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    textAlign: 'right',
    minWidth: 60,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingVertical: 2,
  },
  percentageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 80,
  },
  percentageInput: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    textAlign: 'right',
    minWidth: 40,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingVertical: 2,
  },
  percentageSuffix: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    marginLeft: 2,
  },
  sharesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 80,
  },
  sharesInput: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    textAlign: 'right',
    minWidth: 60,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingVertical: 2,
  },
  adjustmentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 100,
  },
  adjustmentInput: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    textAlign: 'right',
    minWidth: 70,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingVertical: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  footerSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  footerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  footerRight: {
    alignItems: 'flex-end',
  },
  footerText: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.montserratRegular,
    color: Colors.textSecondary,
  },
  footerAmount: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.poppinsSemiBold,
    color: Colors.textPrimary,
  },
  footerRemaining: {
    fontSize: FontSize.sm,
    fontFamily: FontFamily.montserratMedium,
    color: Colors.success,
  },
});
