import { Colors } from '@/constants/colors';
import { BorderRadius, Shadow, Spacing } from '@/constants/spacing';
import { FontFamily, FontSize } from '@/constants/typography';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
    backgroundColor: Colors.white,
  },
  backButton: {
    padding: Spacing.sm,
  },
  headerTitle: {
    fontSize: FontSize.lg,
    fontWeight: '600',
    color: Colors.textPrimary,
    fontFamily: FontFamily.montserratSemiBold,
  },
  content: {
    flex: 1,
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing['2xl'],
  },
  formSection: {
    marginBottom: Spacing['2xl'],
  },
  inputContainer: {
    marginBottom: Spacing.lg,
  },
  label: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.poppinsMedium,
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
  },
  input: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    fontSize: FontSize.md,
    fontFamily: FontFamily.poppinsRegular,
    color: Colors.textPrimary,
    backgroundColor: Colors.white,
  },
  inputFocused: {
    borderColor: Colors.primary,
  },
  inputError: {
    borderColor: Colors.error,
  },
  errorText: {
    fontSize: FontSize.sm,
    color: Colors.error,
    marginTop: Spacing.xs,
    fontFamily: FontFamily.montserratRegular,
  },
  passwordContainer: {
    position: 'relative',
  },
  passwordToggle: {
    position: 'absolute',
    right: Spacing.lg,
    top: '50%',
    transform: [{ translateY: -12 }],
  },
  buttonContainer: {
    marginTop: Spacing['2xl'],
  },
  signupButton: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.lg,
    alignItems: 'center',
    marginBottom: Spacing.lg,
    ...Shadow.base,
  },
  signupButtonText: {
    fontSize: FontSize.lg,
    fontWeight: '600',
    color: Colors.white,
    fontFamily: FontFamily.poppinsSemiBold,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.lg,
    gap: Spacing.sm,
    ...Shadow.sm,
  },
  googleIcon: {
    width: 20,
    height: 20,
  },
  googleButtonText: {
    fontSize: FontSize.lg,
    fontWeight: '500',
    color: Colors.textPrimary,
    fontFamily: FontFamily.poppinsMedium,
  },
  loginPrompt: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: Spacing['2xl'],
  },
  loginPromptText: {
    fontSize: FontSize.md,
    color: Colors.textSecondary,
    fontFamily: FontFamily.montserratRegular,
  },
  loginLink: {
    fontSize: FontSize.md,
    color: Colors.primary,
    fontWeight: '600',
    fontFamily: FontFamily.poppinsSemiBold,
    marginLeft: Spacing.xs,
  },
  termsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: Spacing.xl,
    marginBottom: Spacing.lg,
  },
  termsText: {
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    lineHeight: 20,
    fontFamily: FontFamily.montserratRegular,
  },
  termsLink: {
    color: Colors.primary,
    fontFamily: FontFamily.poppinsMedium,
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  namePhotoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: Spacing.lg,
    gap: Spacing.md,
  },
  nameInputContainer: {
    flex: 1,
  },
  inputWrapper: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingBottom: Spacing.sm,
    paddingTop: Spacing.md,
    position: 'relative',
  },
  inputWrapperError: {
    borderBottomColor: Colors.error,
  },
  floatingLabel: {
    position: 'absolute',
    top: Spacing.md,
    left: 0,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    fontFamily: FontFamily.montserratRegular,
  },
  floatingLabelError: {
    color: Colors.error,
  },
  textInput: {
    fontSize: FontSize.md,
    fontFamily: FontFamily.poppinsRegular,
    color: Colors.textPrimary,
    paddingTop: Spacing.xl,
    paddingBottom: Spacing.xs,
    minHeight: 44,
  },
  errorIcon: {
    position: 'absolute',
    right: 0,
    top: '50%',
    transform: [{ translateY: -10 }],
  },
  photoButtonInline: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.border,
    position: 'relative',
    marginTop: Spacing.md,
  },
  profileImageInline: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  placeholderContainer: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderText: {
    fontSize: FontSize['2xl'],
  },
  photoButtonPlusIcon: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.white,
  },
  eyeIcon: {
    position: 'absolute',
    right: 0,
    top: Spacing.md,
    padding: Spacing.xs,
  },
  helperText: {
    fontSize: FontSize.xs,
    color: Colors.textTertiary,
    marginTop: Spacing.xs,
    fontFamily: FontFamily.montserratRegular,
  },
  phoneRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  countryPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: Spacing.md,
    paddingBottom: Spacing.sm,
    gap: Spacing.xs,
  },
  flagContainer: {
    marginRight: Spacing.xs,
  },
  flag: {
    width: 24,
    height: 16,
    borderRadius: BorderRadius.sm,
    overflow: 'hidden',
    flexDirection: 'row',
  },
  flagOrange: {
    flex: 1,
    backgroundColor: '#FF9933',
  },
  flagWhite: {
    flex: 1,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flagGreen: {
    flex: 1,
    backgroundColor: '#138808',
  },
  countryCode: {
    fontSize: FontSize.md,
    color: Colors.textPrimary,
    fontFamily: FontFamily.poppinsMedium,
  },
  phoneInputWrapper: {
    flex: 1,
  },
  currencyContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: Spacing.lg,
    marginTop: Spacing.md,
  },
  currencyText: {
    fontSize: FontSize.md,
    color: Colors.textSecondary,
    fontFamily: FontFamily.montserratRegular,
  },
  currencyValue: {
    fontSize: FontSize.md,
    color: Colors.primary,
    fontFamily: FontFamily.poppinsMedium,
  },
  changeButton: {
    fontSize: FontSize.md,
    color: Colors.primary,
    fontFamily: FontFamily.poppinsMedium,
  },
  doneButton: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.lg,
    alignItems: 'center',
    marginTop: Spacing.xl,
    ...Shadow.base,
  },
  doneButtonText: {
    fontSize: FontSize.lg,
    fontWeight: '600',
    color: Colors.white,
    fontFamily: FontFamily.poppinsSemiBold,
  },
});
